[build]
buildCommand = "npm ci && npm run contracts:generate && npm run build --workspace superartillery-server"

[deploy]
startCommand = "npm start --workspace superartillery-server"
healthcheckPath = "/api/v1/health"
restartPolicyType = "ON_FAILURE"